# Introduction to Python: Writing a functions

Although there are a lot buit-in functions in Python you can use, the power of learning a programming language is the ability to define your own functions!

In this notebook we learn how to write our own functions.

Let's start with a simple example:

write a function that takes in an integer and checks if that number is even:

In [11]:
# Alternative Solution
def even_check(number):
    if number % 2 == 0:
        print(number, 'is even.')
    else:
        print(number, 'is odd.')

In [12]:
even_check(4)

4 is even.

In [13]:
# what happens if I plug in a float
even_check(5.2)

5.2 is odd.

Let's change the above code so that if the input is not an integer prints a warning.

In [21]:
def even_check(number):
    if type(number) == int:
      if number % 2 == 0:
        print(number, 'is even.')
      else:
        print(number, 'is odd.')
    else:
      print(' Warning: ', number, 'is not an integer')

In [22]:
even_check(5.2)

 Warning:  5.2 is not an integer

Sometimes we need a function of several variables but also a default value for a variable.

In [30]:
def divisible_by(x, y=2):
    if x%y == 0:
        print("Yes.", x, "is divisible by", y)
    else:
        print("No.", x, "is not divisble by", y)

In [31]:
divisible_by(10)

Yes. 10 is divisible by 2

In [32]:
## we can change the default value:

divisible_by(10,3)

No. 10 is not divisble by 3

In [25]:
## Write a function that takes in three numbers and return their avaerage.
def average(num1, num2, num3):
  return (num1 + num2 + num3)/3

In [26]:
average(1,2,3)

2.0

In [34]:
### Write a function that takes in a positive integer n and computes the sum of all numbers from 1 to n
def sum_numbers(n):
  sum = 0
  for i in range(1,n+1):
    sum += i
  return sum

In [33]:
## you code:
### Write a function that takes in a positive integer n and computes the sum of even numbers from 1 to n

In [35]:
# Write a function that takes in n and compute the sum of the first n terms of the harmonic series
# 1 + 1/2 + 1/3 + ... + 1/n

In [43]:
#This function computes how long it takes to pay off a loan. Modify it to also calculate your interest
import numpy as np

def pay_off(balance, annual_rate, monthly_payment):
  month = 0
  monthly_rate = np.exp(np.log(1 + annual_rate)/12.0) - 1
  monthly_factor = 1 + monthly_rate
  while balance >0:
    print("%4d: %4.2f" %(month, balance))
    balance = monthly_factor*balance - monthly_payment
    month = month + 1
  print("\n%d months to pay off your loan" %(month))

In [41]:
pay_off(5000,0.09, 150 )

   0: 5000.00
   1: 4886.04
   2: 4771.25
   3: 4655.64
   4: 4539.19
   5: 4421.91
   6: 4303.78
   7: 4184.80
   8: 4064.96
   9: 3944.26
  10: 3822.69
  11: 3700.24
  12: 3576.91
  13: 3452.69
  14: 3327.57
  15: 3201.55
  16: 3074.63
  17: 2946.79
  18: 2818.03
  19: 2688.34
  20: 2557.71
  21: 2426.15
  22: 2293.63
  23: 2160.16
  24: 2025.73
  25: 1890.33
  26: 1753.96
  27: 1616.60
  28: 1478.25
  29: 1338.90
  30: 1198.55
  31: 1057.19
  32: 914.81
  33: 771.40
  34: 626.96
  35: 481.48
  36: 334.95
  37: 187.37
  38: 38.72

39 months to pay off your loan